export const IS_CLIENT_REGISTERED = "IS_CLIENT_REGISTERED";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const VACANT_INPUT_ALERT = "EMPTY_INPUT_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const SHOW_SIDE_BAR = "SHOW_SIDE_BAR"

export const LOGOUT_USER = "LOGOUT_USER"

export const CLEAR_ADDJOB_INPUT = "CLEAR_ADDJOB_INPUT"

export const ADD_JOB_BEGIN = "ADD_JOB_BEGIN"
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS"
export const ADD_JOB_FAILED = "ADD_JOB_FAILED"

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN"
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS"
export const EDIT_JOB_FAILED = "EDIT_JOB_FAILED"

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN"
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS"
export const DELETE_JOB_FAILED = "DELETE_JOB_FAILED"

export const EDIT_PROFILE_BEGIN = "EDIT_PROFILE_BEGIN"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED"

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN"
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS"

export const GET_PRIORITY_JOBS_BEGIN = "GET_PRIORITY_JOBS_BEGIN"
export const GET_PRIORITY_JOBS_SUCCESS = "GET_PRIORITY__JOBS_SUCCESS"

export const SET_EDIT_JOB = "SET_EDIT_JOB"

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN"
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS"
export const SHOW_STATS_FAILED = "SHOW_STATS_FAILED"

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_IMAGE_BEGIN"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED"

export const UPDATE_PASSWORD_BEGIN = "UPDATE_PASSWORD_BEGIN"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED"
